N_importance: 64
N_samples: 64
black_back: true
chunk: 8192
dataset_name: llff
exp_name: vasedeck_snowy
fusion_split_channel: true
img_wh:
- 640
- 480
model_type:
- nerf_tcnn
- color_field
- window_embedding
- fusion_layer
- feature_field
root_dir: ./data/vasedeck
spheric_poses: true
unet_receipt: default
use_disp: true
